os: linux

dist: xenial

language: c

compiler: gcc

branches:
  only:
    - dev

install:
  - mkdir travis-build
  - cd travis-build
  - cmake .. -DWITH_OPENSSL=1
  - make

before_script:
  - cd -
  - pip install --user cpp-coveralls

script:
  - ./tests/unit/link_unit_test

