os: linux

dist: xenial

language: c

compiler: gcc

branches:
  only:
    - dev

install:
  - mkdir build-travis
  - cd build-travis
  - cmake .. -DWITH_OPENSSL=1
  - make

before_script:
  - pip install --user cpp-coveralls

script:
  - ./tests/unit/link_unit_test

